AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HIPAA chatbot demo with Lambda + Bedrock

Globals:
  Function:
    Timeout: 15
    Runtime: python3.11
    MemorySize: 512

Resources:
  HipaaChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Environment:
        Variables:
          BEDROCK_MODEL_ID: anthropic.claude-3-haiku-20240307
      Events:
        Api:
          Type: Api
          Properties:
            Path: /chat
            Method: post

Outputs:
  ApiUrl:
    Description: API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat"
